language: python
sudo: required
dist: xenial
python:
  - 3.7
install:
  - pipenv run python -m pip install -U pip
  - pipenv install --dev --ignore-pipfile
before_script:
  - cp .extraction.ini extraction.ini
script:
  - pipenv run pytest --cov=. --cov-config=.coveragerc --cov-report=xml
after_success:
  - codecov
